{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-common
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/common_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/common/common_{{ version }}.tar.gz
  sha256: 50d0f4e4aa95b58397750f3de7699746f2a2f3624dd00d5933f06ab5662483fe

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-this.path
  run:
    - r-base
    - r-this.path

test:
  commands:
    - $R -e "library('common')"           # [not win]
    - "\"%R%\" -e \"library('common')\""  # [win]

about:
  home: https://common.r-sassy.org
  dev_url: https://github.com/dbosak01/common/
  license: CC0-1.0
  summary: Contains functions for solving commonly encountered problems while programming in R. This package is intended to provide a lightweight supplement to Base R, and will be useful for almost any R user.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: common
# Type: Package
# Title: Solutions for Common Problems in Base R
# Version: 1.0.5
# Authors@R: c( person(given = "David", family = "Bosak", role = c("aut", "cre"), email = "dbosak01@gmail.com"), person(given = "Andrew", family = "Simmons", role = c("aut"), email = "akwsimmo@gmail.com"), person(given = "Duong", family = "Tran", role = c("ctb"), email = "trand000@aol.com") )
# Maintainer: David Bosak <dbosak01@gmail.com>
# Description: Contains functions for solving commonly encountered problems while programming in R. This package is intended to provide a lightweight supplement to Base R, and will be useful for almost any R user.
# License: CC0
# Encoding: UTF-8
# URL: https://common.r-sassy.org
# BugReports: https://github.com/dbosak01/common/issues
# Depends: R (>= 3.6.0)
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0), glue
# Enhances: base
# Imports: this.path, utils
# Config/testthat/edition: 3
# RoxygenNote: 7.2.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-09-27 23:36:25 UTC; dbosa
# Author: David Bosak [aut, cre], Andrew Simmons [aut], Duong Tran [ctb]
# Repository: CRAN
# Date/Publication: 2022-09-29 08:10:12 UTC
